spring:
  application:
    name: minibank
  datasource:
    url: jdbc:postgresql://localhost:5432/minibank
    username: c0nf1dxnt
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: minibank